### PR TITLE
Convert object ids to object names

### LINKED ISSUE #106: Refactor: Replace object id with object name in variables/parameters
I often copy old CAL methods via textexport to al. 
The first step is removing the @ and the id in the variables and parameters. 
The second step is replacing all ``Record <Id>``; occurences with the correct object name.
e.g. ``Record 27;`` will be replaced with ``Record Item;``

Would be great, if I could do this with the quick actions. (maybe even for all variables and parameters in this method or this object)

Same for ``Codeunit <Id>``, ``Report <id>``, etc.

### PR DESCRIPTION
**Pull request by dannoe**
This will fix #106  

I'm going to transform this to an command-palette action to fix the whole file, instead of fixing single variables.

Tips and feedback will be gladly accepted. 👍🏼

### CODE REVIEW

**Comment by DavidFeldhoff** [comment]
My first PR 🥳
Maybe we can see that as a chance to get in contact and we'll develop it together in a session? This week is quite busy with dynamicscon etc., but maybe we can catch up at the weekend. Would do you think?

**Comment by dannoe** [comment]
I'm very busy the next time and I can't say exactly when I'll find time for it. But feel free to push changes to my branch or make comments about it.

**Comment by tinfister** [comment]
Looking forward to this one. Hope you'll both find time to finish the PR

**Comment by dannoe** [comment]
I'm sorry, but I have some bad news. @tinfister 
We just converted our old C/AL app completely to AL (as BaseApp) and now we use this code to copy&paste.
I won't put any more work into it from my side, as I don't need the feature anymore at the moment.

@DavidFeldhoff Sorry for ruining your first PR :(

Feel free to do whatever you want with my code.

**Comment by DavidFeldhoff** [comment]
I'll close this PR as Andrzej picked this one up in his extension.
The command in the "AZ AL Dev Tools/AL Code Outline" extension is called "Convert Object Ids to Names in the Active Project"
https://github.com/anzwdev/al-code-outline#code-transformation-commands

**Pull request closed without merging**
