### PR TITLE
Loop all hover messages

### LINKED ISSUE #136: Randomly get variant parameters when creating procedures or events
Hi David,

I really love the feature for creating stubs for missing events and procedures!

But sometimes I get Variant parameters instead of the actual datatype, and I just cannot get my head around when this happens. It feels random, but I assume that it is not...

Instead of this:
`internal procedure OnAfterMyEvent(pMyRecord Record "My Table"; pMyOtherRecord Record "My Other Table"; FirstBool: Boolean; SecondBool: Boolean)`

I get this:
`internal procedure OnAfterMyEvent(arg1: Variant; arg2: Variant; arg3: Variant; arg4: Variant)`

Sometimes I even get 
`internal procedure OnAfterMyEvent(pMyRecord Record "My Table"; arg1: Variant; arg2: Variant; arg3: Variant)`

One procedure did not work yesterday, so I just uncommented the line to dive into later. Today the very same procedure worked one time, but when I deleted the created procedure and recreated it I got `arg1: Variant` parameters again 😕

Any idea on what is happening?

### PR DESCRIPTION
**Pull request by jwikman**
Fix  #136.

This change loops all hover messages when trying to parse the data types of parameters.

What do you think?

### CODE REVIEW

**Comment by jwikman** [comment]
Hmmm, the DevOps pipelines didn't seem to like this PR. But I'm not sure that this really has to do with my code change?

**Comment by jwikman** [comment]
The reasons for the pipeline failure could be that those OS versions has been deprecated in DevOps pipelines. See https://docs.microsoft.com/en-us/azure/devops/release-notes/2021/sprint-196-update and https://devblogs.microsoft.com/devops/hosted-pipelines-image-deprecation/

**Comment by DavidFeldhoff** [comment]
Hi Johannes, sorry for leaving you alone with the errors :D yes, that's right, the pipeline isn't working, but as I did not receive any PRs until now, I didn't care that much and have not looked into it yet. Sorry that I've confused you with that!

I won't be able to check the PR today, so I'll look into it tomorrow. But after reading your comments, it sounds very good. Thanks for your work and help :)

**Comment by jwikman** [comment]
It's no panic David, take your time. I've got an easy workaround for now. :)

**Comment by DavidFeldhoff** [comment]
I just updated the images, so that they're using always the latest ones and merged it into your branch to restart the checks. Looks better now ^^
The change as such is looking good. I think I wouldn't have thought that the hover messages are the issue there, so thanks again for helping! I'll merge it and publish it togehter with a few other smaller changes the next days.

Best regards
David

**Comment by jwikman** [comment]
Thanks @DavidFeldhoff 👍

**Pull request merged**
